<?php $items=$items??[]; $overview=$overview??[]; $policy=$premium_policy??[]; $filters=$filters??[]; $statuses=$statuses??[]; $pagination = $pagination ?? ['page'=>1,'total_pages'=>1,'total'=>0]; ?>
<h3 class="mb-3">Duelo de Compatibilidade · Administração</h3>
<div class="row g-3 mb-3"><div class="col-md-3"><div class="rd-card rd-kpi"><div class="card-body"><div class="small text-muted">Gerados</div><div class="value"><?= (int) ($overview['duels_generated'] ?? 0) ?></div></div></div></div><div class="col-md-3"><div class="rd-card rd-kpi"><div class="card-body"><div class="small text-muted">Participação</div><div class="value"><?= e((string) ($overview['engagement_rate_percent'] ?? 0)) ?>%</div></div></div></div><div class="col-md-3"><div class="rd-card rd-kpi"><div class="card-body"><div class="small text-muted">Ações pós-voto</div><div class="value"><?= (int) ($overview['actions_total'] ?? 0) ?></div></div></div></div><div class="col-md-3"><div class="rd-card"><div class="card-body small">Free/Premium por dia: <?= (int) ($policy['free_daily_duels'] ?? 1) ?> / <?= (int) ($policy['premium_daily_duels'] ?? 1) ?><br>Insights premium: <strong><?= !empty($policy['premium_insights_enabled']) ? 'ativos' : 'off' ?></strong></div></div></div></div>
<div class="rd-card mb-3"><div class="card-body"><form class="row g-2 align-items-end" method="get">
<div class="col-md-2"><label class="form-label mb-1">Status</label><select class="form-select form-select-sm" name="status"><option value="">todos</option><?php foreach ($statuses as $status): ?><option value="<?= e((string) $status) ?>" <?= (($filters['status'] ?? '') === $status) ? 'selected' : '' ?>><?= e((string) $status) ?></option><?php endforeach; ?></select></div>
<div class="col-md-2"><label class="form-label mb-1">User ID</label><input class="form-control form-control-sm" name="user_id" value="<?= e((string) ($filters['user_id'] ?? '')) ?>"></div>
<div class="col-md-2"><label class="form-label mb-1">Com ação</label><select class="form-select form-select-sm" name="only_with_action"><option value="0">todos</option><option value="1" <?= (int) ($filters['only_with_action'] ?? 0) === 1 ? 'selected' : '' ?>>somente com ação</option></select></div>
<div class="col-md-2"><label class="form-label mb-1">De</label><input type="date" class="form-control form-control-sm" name="from" value="<?= e((string) ($filters['from'] ?? '')) ?>"></div>
<div class="col-md-2"><label class="form-label mb-1">Até</label><input type="date" class="form-control form-control-sm" name="to" value="<?= e((string) ($filters['to'] ?? '')) ?>"></div>
<div class="col-auto"><button class="btn btn-sm btn-outline-primary">Filtrar</button></div></form></div></div>
<div class="rd-card"><div class="card-body table-responsive"><table class="table table-modern"><thead><tr><th>ID</th><th>User</th><th>Status</th><th>Premium</th><th>Ações</th><th></th></tr></thead><tbody><?php if($items===[]): ?><tr><td colspan="6" class="small text-muted">Sem duelos.</td></tr><?php endif; ?><?php foreach($items as $item): ?><tr><td>#<?= (int) $item['id'] ?></td><td><a href="<?= e(url((string) ($item['links']['user'] ?? '/admin/users'))) ?>">#<?= (int) $item['user_id'] ?></a></td><td><?= e((string) ($item['status'] ?? '')) ?></td><td><?= !empty($item['user_is_premium']) ? 'premium' : 'free' ?></td><td><?= (int) ($item['actions_total'] ?? 0) ?> (invite <?= (int) ($item['invite_actions'] ?? 0) ?>)</td><td><a class="btn btn-sm btn-outline-secondary" href="<?= e(url((string) ($item['links']['audit'] ?? '/admin/audit'))) ?>">audit</a></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php if ((int) ($pagination['total_pages'] ?? 1) > 1): ?>
<div class="small text-muted mt-2">
  Página <?= (int) ($pagination['page'] ?? 1) ?> de <?= (int) ($pagination['total_pages'] ?? 1) ?> · total <?= (int) ($pagination['total'] ?? 0) ?> registos
</div>
<?php endif; ?>
