<?php

use App\Controllers\ActivationController;
use App\Controllers\AuthController;
use App\Controllers\BlockController;
use App\Controllers\ConnectionController;
use App\Controllers\DiscoverController;
use App\Controllers\FavoriteController;
use App\Controllers\FeedController;
use App\Controllers\MatchController;
use App\Controllers\MessageController;
use App\Controllers\NotificationController;
use App\Controllers\ProfileController;
use App\Controllers\ReportController;
use App\Controllers\SubscriptionController;
use App\Controllers\SwipeController;

$router->add('GET', '/activation', [ActivationController::class, 'show']);
$router->add('POST', '/activation/pay', [ActivationController::class, 'pay']);
$router->add('GET', '/activation/status', [ActivationController::class, 'status']);
$router->add('GET', '/subscription/status', [SubscriptionController::class, 'status']);
$router->add('POST', '/subscription/renew', [SubscriptionController::class, 'renew']);
$router->add('GET', '/dashboard', [AuthController::class, 'dashboard']);
$router->add('GET', '/discover', [DiscoverController::class, 'index']);
$router->add('GET', '/swipe', [SwipeController::class, 'index']);
$router->add('POST', '/swipe/action', [SwipeController::class, 'action']);
$router->add('GET', '/matches', [MatchController::class, 'index']);
$router->add('GET', '/profile', [ProfileController::class, 'index']);
$router->add('POST', '/profile/update', [ProfileController::class, 'update']);
$router->add('POST', '/profile/photo', [ProfileController::class, 'photo']);
$router->add('POST', '/profile/gallery', [ProfileController::class, 'gallery']);
$router->add('GET', '/messages', [MessageController::class, 'index']);
$router->add('GET', '/messages/{conversation}', [MessageController::class, 'show']);
$router->add('POST', '/messages/send', [MessageController::class, 'send']);
$router->add('GET', '/feed', [FeedController::class, 'index']);
$router->add('POST', '/feed/post', [FeedController::class, 'post']);
$router->add('POST', '/feed/like', [FeedController::class, 'like']);
$router->add('POST', '/feed/comment', [FeedController::class, 'comment']);
$router->add('GET', '/notifications', [NotificationController::class, 'index']);
$router->add('POST', '/favorite/toggle', [FavoriteController::class, 'toggle']);
$router->add('POST', '/block', [BlockController::class, 'store']);
$router->add('POST', '/report', [ReportController::class, 'store']);
$router->add('POST', '/connection/request', [ConnectionController::class, 'request']);
$router->add('POST', '/connection/accept', [ConnectionController::class, 'accept']);
