<?php $items=$items??[]; $overview=$overview??[]; $filters=$filters??[]; $pagination = $pagination ?? ['page'=>1,'total_pages'=>1,'total'=>0]; $statuses = $statuses ?? []; $categories = $categories ?? []; $reportStatuses = $report_statuses ?? []; ?>
<h3 class="mb-3">Histórias Anónimas · Moderação</h3>
<div class="row g-3 mb-3"><div class="col-md-3"><div class="rd-card rd-kpi"><div class="card-body"><div class="small text-muted">Publicadas</div><div class="value"><?= (int) ($overview['stories_published'] ?? 0) ?></div></div></div></div><div class="col-md-3"><div class="rd-card rd-kpi"><div class="card-body"><div class="small text-muted">Denúncias pendentes</div><div class="value"><?= (int) ($overview['reports_pending'] ?? 0) ?></div></div></div></div><div class="col-md-3"><div class="rd-card rd-kpi"><div class="card-body"><div class="small text-muted">Story of day</div><div class="value"><?= (int) ($overview['story_of_day_total'] ?? 0) ?></div></div></div></div><div class="col-md-3"><div class="rd-card rd-kpi"><div class="card-body"><div class="small text-muted">Moderadas</div><div class="value"><?= (int) ($overview['moderated_total'] ?? 0) ?></div></div></div></div></div>
<div class="rd-card mb-3"><div class="card-body"><form class="row g-2 align-items-end" method="get">
<div class="col-md-2"><label class="form-label mb-1">Status</label><select class="form-select form-select-sm" name="status"><option value="">todos</option><?php foreach ($statuses as $status): ?><option value="<?= e((string) $status) ?>" <?= (($filters['status'] ?? '') === $status) ? 'selected' : '' ?>><?= e((string) $status) ?></option><?php endforeach; ?></select></div>
<div class="col-md-2"><label class="form-label mb-1">Categoria</label><select class="form-select form-select-sm" name="category"><option value="">todas</option><?php foreach ($categories as $category): ?><option value="<?= e((string) $category) ?>" <?= (($filters['category'] ?? '') === $category) ? 'selected' : '' ?>><?= e((string) $category) ?></option><?php endforeach; ?></select></div>
<div class="col-md-2"><label class="form-label mb-1">Report</label><select class="form-select form-select-sm" name="report_status"><option value="">todos</option><?php foreach ($reportStatuses as $status): ?><option value="<?= e((string) $status) ?>" <?= (($filters['report_status'] ?? '') === $status) ? 'selected' : '' ?>><?= e((string) $status) ?></option><?php endforeach; ?></select></div>
<div class="col-md-2"><label class="form-label mb-1">Autor ID</label><input class="form-control form-control-sm" name="author_user_id" value="<?= e((string) ($filters['author_user_id'] ?? '')) ?>"></div>
<div class="col-md-2"><label class="form-label mb-1">Apenas denunciadas</label><select class="form-select form-select-sm" name="only_reported"><option value="0">não</option><option value="1" <?= (int) ($filters['only_reported'] ?? 0) === 1 ? 'selected' : '' ?>>sim</option></select></div>
<div class="col-auto"><button class="btn btn-sm btn-outline-primary">Filtrar</button></div></form></div></div>
<div class="rd-card"><div class="card-body table-responsive"><table class="table table-modern"><thead><tr><th>ID</th><th>Status</th><th>Categoria</th><th>Autor</th><th>Denúncias</th><th></th></tr></thead><tbody>
<?php if ($items===[]): ?><tr><td colspan="6" class="small text-muted">Sem histórias.</td></tr><?php endif; ?>
<?php foreach($items as $item): ?><tr><td>#<?= (int) $item['id'] ?></td><td><?= e((string) ($item['status'] ?? '')) ?><?php if (!empty($item['is_story_of_day'])): ?> · dia<?php endif; ?></td><td><?= e((string) ($item['category'] ?? '')) ?></td><td><a href="<?= e(url((string) ($item['links']['author'] ?? '/admin/users'))) ?>">#<?= (int) $item['author_user_id'] ?></a></td><td><?= (int) ($item['reports_total'] ?? 0) ?> (pend <?= (int) ($item['reports_pending'] ?? 0) ?>)</td><td><a class="btn btn-sm btn-rd-soft" href="<?= e(url((string) ($item['links']['detail'] ?? '/admin/anonymous-stories'))) ?>">Detalhe</a></td></tr><?php endforeach; ?>
</tbody></table></div></div>
<?php if ((int) ($pagination['total_pages'] ?? 1) > 1): ?>
<div class="small text-muted mt-2">
  Página <?= (int) ($pagination['page'] ?? 1) ?> de <?= (int) ($pagination['total_pages'] ?? 1) ?> · total <?= (int) ($pagination['total'] ?? 0) ?> registos
</div>
<?php endif; ?>
